# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>
