require 'rails_helper'
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TerritoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Territory. As you add validations to Territory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.build(:territory).attributes
  }

  describe "GET #index" do
    it "assigns all territories as @territories" do
      territory = Territory.create! valid_attributes
      get :index, params: {}
      expect(assigns(:territories)).to eq([territory])
    end
  end

  describe "GET #show" do
    it "assigns the requested territory as @territory" do
      territory = Territory.create! valid_attributes
      get :show, params: {id: territory.to_param}
      expect(assigns(:territory)).to eq(territory)
    end
  end

  describe "GET #edit" do
    it "assigns the requested territory as @territory" do
      territory = Territory.create! valid_attributes
      params = {id: territory.to_param}
      get :edit, params: params
      ModelWizard.new(territory, session, params).start
      expect(assigns(:territory)).to eq(territory)
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it "updates the requested territory" do
        territory = Territory.create! valid_attributes
        get :edit, params: {id: territory.to_param}
        put :update, params: {id: territory.to_param, territory: { start_date: "2017-01-01" }}
        expect(assigns(:territory).reload.start_date).to eq("2017-01-01")
      end

      it "assigns the requested territory as @territory" do
        territory = Territory.create! valid_attributes
        get :edit, params: {id: territory.to_param}
        put :update, params: {id: territory.to_param, territory: valid_attributes}
        expect(assigns(:territory)).to eq(territory)
      end

      it "redirects to the territory" do
        territory = Territory.create! valid_attributes
        get :edit, params: {id: territory.to_param}
        put :update, params: {id: territory.to_param, territory: valid_attributes}
        expect(response).to redirect_to root_path
      end
    end
  end

end
